#HERE WE WILL SEE SOME GIT BASH SHOTCUT CODE TO MAKE CHANGES IN OUR FOLDER
#THIS PROGRAM IS JUST TO REMEMBER THE SHOTCUT CODE 
#1ST : pwd :PRINT WITH DIRECTORY (DIRECTORY = FOLDER)
#IT IS USE TO KNOW WHERE OUT GIT BASH IS PRESENT RIGHT NOW
#2ND : ls : LIST
#IT IS USE TO LISTALL THE FILES AND FOLDER PRESENT IN THAT DIRECTORY
#3RD : cd : CHANGE DIRECTORY
#IT IS USE TO CHANGE THE FOLDER FROM ONE TO ANOTHER AND MANAGE IT
#TO MAKE IT PERFORM WE NEED TO TYPE LIKE : cd E://(NAME OF THE FOLDER)
#4TH : cd .. 
#IT IS USE TO GO BACK OUT OF THE FOLDER
#5TH : rm : REMOVE
#IT IS USE TO REMOVE THE FILE THAT IS EXISTING
#6TH : rm -rf
#IT IS USE TO DELETE FOLDER 
#7TH : clear 
#IT IS USE TO CLEAR THE SCREEN
